version: '3.7'

services:
    nginx:
        image: nginx:latest
        container_name: nginx
        volumes:
            - ./docker/nginx.conf:/etc/nginx/nginx.conf
            - ./src:/var/www
        ports:
            - "7777:80"
        depends_on:
            - php

    php:
        build:
            context: ./docker
        container_name: php
        volumes:
            - ./src:/var/www

    mysql:
        image: mysql:8.3
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: db
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        volumes:
            - mysql_data:/var/lib/mysql
        ports:
            - "3306:3306"

volumes:
    mysql_data:
